### ISSUE TITLE
Implement Dlr CRUD

### ISSUE THREAD

**Issue by husamettinarabaci** [octoposprime/op-be-dlr#3]
Please implement basic crud operations of the dlr system.

**Comment by Sddilora** [comment]
https://github.com/octoposprime/op-be-user/blob/phase1/internal/application/service/user.go

This is the user service's CRUD operations.

@octoposprime/be 
@octoposprime/be-tl 
@octoposprime/be-jr 

Everyone needs to understand how the CRUD operations are implemented in the user service so that we can comprehend the project, DDD structure, and implement the DLR service.

**Comment by Sddilora** [comment]
We have dlr services basic implementations on https://github.com/octoposprime/op-be-dlr/tree/first/hsm/2/create-first-project branch. We need to change https://github.com/octoposprime/op-be-dlr/blob/first/hsm/2/create-first-project/internal/application/service/dlr.go CRUD operations in here those are caming from user service and they are not fit to dlr srvice. 
- [ ] [CreateDlr](https://github.com/octoposprime/op-be-dlr/issues/5)
- [ ] [UpdateDlrBase](https://github.com/octoposprime/op-be-dlr/issues/6)
- [ ] [UpdateDlrCore](https://github.com/octoposprime/op-be-dlr/issues/7)
- [ ] [UpdateDlrStatus](https://github.com/octoposprime/op-be-dlr/issues/8)
- [ ] [DeleteDlr](https://github.com/octoposprime/op-be-dlr/issues/9)
